spring:
  datasource:
    url: jdbc:mysql://192.168.43.150:3306/dailyMail?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 1970432392@qq.com
    password: ///////////
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  type-aliases-package: com.github.mqpearth.model.pojo
  mapper-locations: mapper/*.xml

logging:
  level:
    root: WARN